---
title: "Table 7 Lab: Field Dataset Cleaning - Solutions"
format: html
editor: source
author: "Ansita Agrawal, Sage Kruleski, Auster Zhang"
embed-resources: true
code-tools: true
echo: true #always show code
error: true #keep rendering even if errors occur
---

## Preamble

## Load appropriate libraries
```{r}
library(dplyr)
library(tidyverse)
```

## Loading in files
```{r}
v1 <- read_csv("clean_p_regilla_V1_field_data.csv")
v2 <- read_csv("clean_p_regilla_V2_field_data.csv")
```

## Cleaning column headers
```{r}
v1 <- v1 |>
  rename_with(str_to_camel)
v2 <- v2 |>
  rename_with(str_to_camel)
```

```{r}
v1 <- v1 |>
  mutate(latitudeManualGps = as.double(latitudeManualGps),
         waterTemperatureC = as.double(waterTemperatureC))
```

## Creating full dataset
```{r}
full <- v2 |>
  full_join(v1, by = join_by(
      globalId, island, site, latitudeManualGps, longitudeManualGps, elevationM,
      sex, totalMassG, bagMassG, waterTemperatureC, x, y,
      collectionDateAndTime == creationDate, 
      sulMm == svlMm, 
      animalMassG == animalWeight, 
      airTemperatureC == airTemperatureC44,
      substrateType == substrate
    )
  )
```


#Question 8 - make a map
```{r}
#required packages
library(tidyverse)
#install.packages("auk")
library(auk)
#install.packages("rebird")
library(rebird)
#install.packages("sf")
library(sf)
#install.packages("terrainr")
library(terrainr)
```

```{r}

full |> 
  filter(x != 0, y != 0)

frog_geo <- st_as_sf(full,coords=c(x = "x", y = "y"),crs="WGS84") #Converts a regular dataframe → sf (simple features) object

frog_geo_buf <- frog_geo |> st_buffer(dist = 5000)

frog_tiles <- get_tiles(frog_geo_buf, services = "USGSTopo", resolution = 200) #Downloads map imagery (tiles) for your spatial extent

ggplot() +
  geom_spatial_rgb(data = frog_tiles$USGSTopo, mapping = aes(x, y, r = red, g = green, b = blue)) +
  geom_sf(data = frog_geo, alpha = .75) +
  labs(title = "xxx", 
       caption="yyy")


```


#notes for making a table with a summary function for body measurements
```{r}
#step 1 = clean site names
clean_names <- full |>
  mutate(
    site = case_when(
      str_detect(str_to_lower(site), "san antonio") ~ "San Antonio creek",
      str_detect(str_to_lower(site), "ucsb") ~ "UCSB North Open Space",
      str_detect(str_to_lower(site), "rattlesnake") ~ "Rattlesnake Canyon Creek",
str_detect(str_to_lower(site), "rattlesnake") ~ "Rattlesnake Canyon Creek",
str_detect(str_to_lower(site), "rocky nook") ~ "Rocky Nook Park",
str_detect(str_to_lower(site), "hazard") ~ "Hazard Creek Beach",
str_detect(str_to_lower(site), "cascada") ~ "Cascada Canyon",
str_detect(str_to_lower(site), "prisoners") ~ "Prisoners Harbor",
str_detect(str_to_lower(site), "valley") ~ "Valley Anchorage Harbor",
str_detect(str_to_lower(site), "del") ~ "Canyon Del Medio",
str_detect(str_to_lower(site), "watt") ~ "Watt Road Pond",
str_detect(str_to_lower(site), "trestle") ~ "Trestle Beach",
str_detect(str_to_lower(site), "bear") ~ "Bear Creek Pond",
str_detect(str_to_lower(site), "field") ~ "SCI Field Station",
str_detect(str_to_lower(site), "1127") ~ "SCI Field Station",
str_detect(str_to_lower(site), "along creek") ~ "SCI Field Station",
      is.na(site) ~ "SCI Field Station",
      TRUE ~ "SCI Field Station"
    )
  )

```


```{r}
library(kableExtra)

#calculate animal mass, remove NA and unknown values for 'sex' so we are only looking at adult frogs
clean_names <- clean_names |> 
  mutate(animalMassG = totalMassG - bagMassG) |> 
 filter(!sex %in% c("UK", "Unknown")) |> 
  drop_na(sex)
unique(clean_names$sex)

#make a function that takes a dataframe and calculates measurement values (mean, sd, min, and max), counts the sample size (n()), and renames columns from user-input columns
frog_summary <- function(data, ..., summary_vars) {
  data |>
    group_by(...) |>
    summarise(
      across(
        {{ summary_vars }},
        list(
          mean = ~ mean(.x, na.rm = TRUE),
          sd = ~ sd(.x, na.rm = TRUE),
          min = ~ min(.x, na.rm = TRUE),
          max = ~ max(.x, na.rm = TRUE)
        ),
        .names = "{.col}_{.fn}"
      ),
      n = n()
    )
}

#prep table by applying function, then ungrouping so table can include island and mainland as group headers
table_data <- clean_names |> 
  frog_summary(island, site, sex, summary_vars = c(sulMm, mass)) |> 
  ungroup() |> 
  arrange(island, site)
  
#create a table that shows mass and sul as table headers for columns and island and mainland for grouped headers for rows
table <- table_data |> 
  select(-island) |> 
   select(site, sex, n, everything()) |> 
  kable(digits = c(0, 1, 1, 0),
        col.names = c("Site", "Sex", "N", "Mean", "SD", "Min", "Max","Mean", "SD", "Min", "Max" ),
        caption = "Pacific chorus frog measurements. Frogs were captured on Santa Cruz Island and along adjacent mainland California sites.") |>
  kable_classic(full_width = F,
                bootstrap_options = "striped") |> 
  add_header_above(c(" " = 3, "SUL (mm)" = 4, "Mass (g)" = 4),
                   bold = TRUE) |> 
  pack_rows("Mainland",
            1,
            sum(table_data$island == "Mainland")) |> 
  pack_rows("Island",
            sum(table_data$island == "Mainland") + 1,
            nrow(table_data)) |> 
  row_spec(row = 0, bold = T, align = "c") |> 
  footnote(general = "SUL is snout urostyle length")
```

